name: Daily Token Generator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12 AM UTC
  workflow_dispatch:    # Allows manual triggering

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run token generator
        run: node Plugins/daily_token_generator.js

      - name: Commit and push token
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add Plugins/daily_token.json
          git commit -m "Update daily token"
          git push
